### ISSUE TITLE
Kick-Off Meeting durchführen

### ISSUE THREAD

**Issue by skyrun2001** [HelpingCall/callForHelp#4]
Wir müssen ein Kick-Off Meeting mit Üpping durchführen.

**Comment by MagnusAlthoff** [comment]
Hätte bis auf Heute Abend an sich jeden Tag Zeit. Am Wochenende logischerweise eher ungerne aber ich denke mal ab Montag sollte es bei mir passen. Würde sagen so ab 9 Uhr wäre ich immer bereit dafür.
